### ISSUE TITLE
leave_all_telegram_groups.py

### ISSUE THREAD

**Issue by FrozenStoneCamper** [ronik56/fux-blog#1]
Hey Ronik, I just found this script on your profile but I dont know how to run it, maybe Im asking a dumb question but actually how do I run that script?!?

**Comment by FrozenStoneCamper** [comment]
Opened an issue here, becuz I cant find a way to contact you.

**Comment by ronik56** [comment]
I replied on the script's page, but you need Python 3 and Telethon installed. 
Then follow the comment on line 4, paste the info of the Telegram account in lines 5-7, and save
Open a command line window in the folder the script is in and run: `python3 leave_all_telegram_groups.py`
You'll get a code to your Telegram account, enter the code in the prompt, and that's it. It will automatically exit all groups of over 200 people on your account.
